[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' http://3.83.224.94:* ws: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
    Referrer-Policy = "no-referrer-when-downgrade"

[[redirects]]
  from = "/api/*"
  to = "http://3.83.224.94/:splat"
  status = 200
  force = true