services:
  backend:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped

volumes:
  postgres_data:
